export {default as NavCom} from './NavCom/NavCom'
export {default as Slider} from './Slider/Slider'
export {default as WhoWe} from './WhoWe/WhoWe'
export {default as HotDeals} from './HotDeals/HotDeals'
export {default as Footer} from './Footer/Footer'